apiVersion: ai-gateway.deere.com/v1
kind: Registration
metadata:
  name: dtc-authoring # must be a globally unique name, lowercase, a-z, 0-9, and -.
  applicationService: cpss_pit # the name of your application service.
content:
  spec:
    compliance:
      generativeAITermsOfUseRevision: NOV2025 # See https://data.deere.com/ai/legal to make sure you understand the terms of use.
      compliesWithGenerativeAITermsOfUse: yes
    description:  Use AI to author DTCs. We will use AI to processing information from code to generate DTCs automatically, which will speed up the process for the support. # verbose description of your application and usage of AI for data processing.
    maxGicpClassification: Company Use # highest level of GICP you plan to use with AI.
    oauthConfigs:
      - oauthClientId: 0oa17ym2irgEPkKQs1t8 # the Okta client ID you created for your application.
        oauthDomain: sso.johndeere.com
    owners:
      - email: melogustavor@johndeere.com
    providers:
      - provider: openai
        models:
        - modelId: gpt-4o-mini-2024-07-18 # any of the models available to use (refer to the spec).
        - modelId: gpt-4o-2024-11-20
        - modelId: gpt-5.2-2025-12-11